"""
Classi COCO (80) di YOLOv8n, raggruppate per categoria semantica.

Usato per catalogare gli oggetti rilevati nelle immagini nel grafo.
"""

# COCO class id → nome classe
COCO_CLASSES: dict[int, str] = {
    0: "person",
    1: "bicycle",
    2: "car",
    3: "motorcycle",
    4: "airplane",
    5: "bus",
    6: "train",
    7: "truck",
    8: "boat",
    9: "traffic light",
    10: "fire hydrant",
    11: "stop sign",
    12: "parking meter",
    13: "bench",
    14: "bird",
    15: "cat",
    16: "dog",
    17: "horse",
    18: "sheep",
    19: "cow",
    20: "elephant",
    21: "bear",
    22: "zebra",
    23: "giraffe",
    24: "backpack",
    25: "umbrella",
    26: "handbag",
    27: "tie",
    28: "suitcase",
    29: "frisbee",
    30: "skis",
    31: "snowboard",
    32: "sports ball",
    33: "kite",
    34: "baseball bat",
    35: "baseball glove",
    36: "skateboard",
    37: "surfboard",
    38: "tennis racket",
    39: "bottle",
    40: "wine glass",
    41: "cup",
    42: "fork",
    43: "knife",
    44: "spoon",
    45: "bowl",
    46: "banana",
    47: "apple",
    48: "sandwich",
    49: "orange",
    50: "broccoli",
    51: "carrot",
    52: "hot dog",
    53: "pizza",
    54: "donut",
    55: "cake",
    56: "chair",
    57: "couch",
    58: "potted plant",
    59: "bed",
    60: "dining table",
    61: "toilet",
    62: "tv",
    63: "laptop",
    64: "mouse",
    65: "remote",
    66: "keyboard",
    67: "cell phone",
    68: "microwave",
    69: "oven",
    70: "toaster",
    71: "sink",
    72: "refrigerator",
    73: "book",
    74: "clock",
    75: "vase",
    76: "scissors",
    77: "teddy bear",
    78: "hair drier",
    79: "toothbrush",
}

# Categoria semantica per classe (per aggregazioni nel grafo)
COCO_CATEGORY: dict[int, str] = {
    0: "person",
    1: "vehicle", 2: "vehicle", 3: "vehicle", 4: "vehicle", 5: "vehicle",
    6: "vehicle", 7: "vehicle", 8: "vehicle",
    9: "infrastructure", 10: "infrastructure", 11: "infrastructure",
    12: "infrastructure", 13: "infrastructure",
    14: "animal", 15: "animal", 16: "animal", 17: "animal", 18: "animal",
    19: "animal", 20: "animal", 21: "animal", 22: "animal", 23: "animal",
    24: "accessory", 25: "accessory", 26: "accessory", 27: "accessory", 28: "accessory",
    29: "sport", 30: "sport", 31: "sport", 32: "sport", 33: "sport",
    34: "sport", 35: "sport", 36: "sport", 37: "sport", 38: "sport",
    39: "food", 40: "food", 41: "food", 42: "food", 43: "food",
    44: "food", 45: "food", 46: "food", 47: "food", 48: "food",
    49: "food", 50: "food", 51: "food", 52: "food", 53: "food",
    54: "food", 55: "food",
    56: "furniture", 57: "furniture", 58: "furniture", 59: "furniture", 60: "furniture",
    61: "furniture",
    62: "electronics", 63: "electronics", 64: "electronics", 65: "electronics",
    66: "electronics", 67: "electronics", 68: "electronics", 69: "electronics",
    70: "electronics", 71: "electronics", 72: "electronics",
    73: "indoor", 74: "indoor", 75: "indoor", 76: "indoor",
    77: "indoor", 78: "indoor", 79: "indoor",
}

# Reverse: nome → COCO id
COCO_IDS: dict[str, int] = {v: k for k, v in COCO_CLASSES.items()}

# Classi da trattare come "persona" (per trigger face recognition)
PERSON_CLASS_ID = 0
